name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: Tjark-Kuehl/dragonflight-talenttrees/.github/actions/node-setup@main
        with:
          node-version: 16
          github-token: ${{ secrets.PRIVATE_TOKEN }}

      - name: Build
        run: pnpm build-only

      - uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
        with:
          branch: main

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist
