name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: Tjark-Kuehl/dragonflight-talenttrees/.github/actions/node-setup@main
        with:
          version: 16

      - name: Build
        run: pnpm build-only

      - uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
        with:
          branch: main
